
alias gs="git status"
alias gc="git commit"
alias gco="git checkout"
alias gcam="git commit -am"
alias gp="git push"
alias gd="git diff"
alias gu="git pull"
alias ga="git add"
alias gm="git merge"
alias ll="ls -la"
alias tailf="tail -f -n 100"
